# Generated by Django 3.1.1 on 2020-09-26 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('codigo_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': 'almacenes',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo_articulo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'articulo',
                'verbose_name_plural': 'articulos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('codigo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='')),
                ('direccion', models.CharField(max_length=50)),
                ('tipo_cliente', models.CharField(choices=[('N', 'Normal'), ('P', 'Plata'), ('O', 'Oro'), ('Pt', 'Platino')], default='N', max_length=10, verbose_name='Tipo de cliente')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='EmpresaAsociada',
            fields=[
                ('codigo_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa asociada',
                'verbose_name_plural': 'empresas asociadas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articulos', models.ManyToManyField(blank=True, to='gestion_pedidos.Articulo')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero_pedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de pedido')),
                ('cantidad', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True)),
                ('urgente', models.BooleanField(default=False)),
                ('tipo_surtidor', models.CharField(choices=[('C', 'Central'), ('S', 'Sucursal'), ('A', 'Empresa asociada')], default='C', help_text='Por favor seleccione a continuación el surtidor según aplique', max_length=10, verbose_name='Quién surtirá el pedido')),
                ('referencia', models.CharField(blank=True, help_text='Sólo para pedidos a sucursales y asociados', max_length=50, null=True)),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle del pedido')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.articulo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.cliente')),
                ('codigo_almacen', models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.almacen')),
                ('codigo_asociado', models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.empresaasociada')),
                ('codigo_sucursal', models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_pedidos.sucursal')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='gestion_pedidos.Proveedor'),
        ),
    ]
